{"name": "[Positive] Verify user can login on saucelabs using correct credentials", "status": "broken", "statusDetails": {"message": "AttributeError: 'generator' object has no attribute 'find_element'", "trace": "set_up = <generator object set_up at 0x0000027883EE6190>\n\n    @step(\"user try login with correct credentials\")\n    @story(\"User can login to website using correct credentials\")\n    @title(\"[Positive] Verify user can login on saucelabs using correct credentials\")\n    def test_login_correct_credentials(set_up):\n        #instance initialization\n        driver = set_up\n        login_page = Login_page(driver)\n        inventory_page = Inventory_page(driver)\n    \n        # Perform login with correct credentials\n        # login_page.login_as(\"standard_user\", \"secret_sauce\")\n>       login_page.insert_credentials(\"standard_user\", \"secret_sauce\")\n\ntests\\test_login.py:132: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\npage\\login_page.py:45: in insert_credentials\n    self.insert_username(username)\npage\\login_page.py:25: in insert_username\n    self.action.double_click(self.get(self.username_col))\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <page.login_page.Login_page object at 0x000002788434D7F0>, identfier = ('id', 'user-name')\n\n    def get(self, identfier:tuple) -> object:\n        \"\"\"Get element object by identifier\n    \n        Args:\n            identfier (tuple): For example, (By.ID, \"user-name\") or else.\n    \n        Returns:\n            object: Element object\n        \"\"\"\n>       return self.driver.find_element(*identfier)\nE       AttributeError: 'generator' object has no attribute 'find_element'\n\npage\\POM.py:77: AttributeError"}, "steps": [{"name": "user try login with correct credentials", "status": "broken", "statusDetails": {"message": "AttributeError: 'generator' object has no attribute 'find_element'\n", "trace": "  File \"C:\\Users\\tan\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\test-package-xh99BTJe-py3.12\\Lib\\site-packages\\allure_commons\\_allure.py\", line 192, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"C:\\QA-practice\\Saucelabs\\python\\tests\\test_login.py\", line 132, in test_login_correct_credentials\n    login_page.insert_credentials(\"standard_user\", \"secret_sauce\")\n  File \"C:\\QA-practice\\Saucelabs\\python\\page\\login_page.py\", line 45, in insert_credentials\n    self.insert_username(username)\n  File \"C:\\Users\\tan\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\test-package-xh99BTJe-py3.12\\Lib\\site-packages\\allure_commons\\_allure.py\", line 192, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"C:\\QA-practice\\Saucelabs\\python\\page\\login_page.py\", line 25, in insert_username\n    self.action.double_click(self.get(self.username_col))\n                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\QA-practice\\Saucelabs\\python\\page\\POM.py\", line 77, in get\n    return self.driver.find_element(*identfier)\n           ^^^^^^^^^^^^^^^^^^^^^^^^\n"}, "steps": [{"name": "Insert username as 'standard_user'", "status": "broken", "statusDetails": {"message": "AttributeError: 'generator' object has no attribute 'find_element'\n", "trace": "  File \"C:\\Users\\tan\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\test-package-xh99BTJe-py3.12\\Lib\\site-packages\\allure_commons\\_allure.py\", line 192, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"C:\\QA-practice\\Saucelabs\\python\\page\\login_page.py\", line 25, in insert_username\n    self.action.double_click(self.get(self.username_col))\n                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\QA-practice\\Saucelabs\\python\\page\\POM.py\", line 77, in get\n    return self.driver.find_element(*identfier)\n           ^^^^^^^^^^^^^^^^^^^^^^^^\n"}, "parameters": [{"name": "username", "value": "'standard_user'"}], "start": 1740992155342, "stop": 1740992155342}], "parameters": [{"name": "set_up", "value": "<generator object set_up at 0x0000027883EE6190>"}], "start": 1740992155342, "stop": 1740992155343}], "start": 1740992155342, "stop": 1740992155344, "uuid": "013abb36-d5e6-45b4-ab23-a9b6f7a64166", "historyId": "cfce530969d8b07c8d2d8c1371bdbbcd", "testCaseId": "cfce530969d8b07c8d2d8c1371bdbbcd", "fullName": "tests.test_login#test_login_correct_credentials", "labels": [{"name": "feature", "value": "Login"}, {"name": "severity", "value": "blocker"}, {"name": "suite", "value": "Validate Login Functionality"}, {"name": "story", "value": "User can login to website using correct credentials"}, {"name": "parentSuite", "value": "tests"}, {"name": "host", "value": "LOQ15"}, {"name": "thread", "value": "14380-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login"}]}